version: '3.9'
services:
        api:
                build:
                        context: .
                ports:
                        - 80:80
                volumes:
                        - ./docker_config.py:/code/default_config.py
        postgres:
                image: postgres:latest
                environment:
                        POSTGRES_USER: flask-app
                        POSTGRES_PASSWORD: flask-app-password
                        POSTGRES_DB: flask-app
                volumes:
                        - ./pg_data:/var/lib/postgresql/data
