version: "3.9"
services:
  api:
    image: twitser/flask-app:version-1
    ports:
    - 80:80
    depends_on:
      postgres:
        condition: service_healthy

    volumes:
      - ./docker_config.py:/code/default_config.py
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: flask-app-password
      POSTGRES_DB: flask-app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
